INSERT INTO provinces (id, name, code, division_type, codename, phone_code, districts)
VALUES (1, 'Thành phố Hà Nội', 1, 'thành phố trung ương', 'thanh_pho_ha_noi', 24, '[]'),
       (2, 'Tỉnh Hà Giang', 2, 'tỉnh', 'tinh_ha_giang', 219, '[]'),
       (3, 'Tỉnh Cao Bằng', 4, 'tỉnh', 'tinh_cao_bang', 206, '[]'),
       (4, 'Tỉnh Bắc Kạn', 6, 'tỉnh', 'tinh_bac_kan', 209, '[]'),
       (5, 'Tỉnh Tuyên Quang', 8, 'tỉnh', 'tinh_tuyen_quang', 207, '[]'),
       (6, 'Tỉnh Lào Cai', 10, 'tỉnh', 'tinh_lao_cai', 214, '[]'),
       (7, 'Tỉnh Điện Biên', 11, 'tỉnh', 'tinh_dien_bien', 215, '[]'),
       (8, 'Tỉnh Lai Châu', 12, 'tỉnh', 'tinh_lai_chau', 213, '[]'),
       (9, 'Tỉnh Sơn La', 14, 'tỉnh', 'tinh_son_la', 212, '[]'),
       (10, 'Tỉnh Yên Bái', 15, 'tỉnh', 'tinh_yen_bai', 216, '[]'),
       (11, 'Tỉnh Hoà Bình', 17, 'tỉnh', 'tinh_hoa_binh', 218, '[]'),
       (12, 'Tỉnh Thái Nguyên', 19, 'tỉnh', 'tinh_thai_nguyen', 208, '[]'),
       (13, 'Tỉnh Lạng Sơn', 20, 'tỉnh', 'tinh_lang_son', 205, '[]'),
       (14, 'Tỉnh Quảng Ninh', 22, 'tỉnh', 'tinh_quang_ninh', 203, '[]'),
       (15, 'Tỉnh Bắc Giang', 24, 'tỉnh', 'tinh_bac_giang', 204, '[]'),
       (16, 'Tỉnh Phú Thọ', 25, 'tỉnh', 'tinh_phu_tho', 210, '[]'),
       (17, 'Tỉnh Vĩnh Phúc', 26, 'tỉnh', 'tinh_vinh_phuc', 211, '[]'),
       (18, 'Tỉnh Bắc Ninh', 27, 'tỉnh', 'tinh_bac_ninh', 222, '[]'),
       (19, 'Tỉnh Hải Dương', 30, 'tỉnh', 'tinh_hai_duong', 220, '[]'),
       (20, 'Thành phố Hải Phòng', 31, 'thành phố trung ương', 'thanh_pho_hai_phong', 225, '[]'),
       (21, 'Tỉnh Hưng Yên', 33, 'tỉnh', 'tinh_hung_yen', 221, '[]'),
       (22, 'Tỉnh Thái Bình', 34, 'tỉnh', 'tinh_thai_binh', 227, '[]'),
       (23, 'Tỉnh Hà Nam', 35, 'tỉnh', 'tinh_ha_nam', 226, '[]'),
       (24, 'Tỉnh Nam Định', 36, 'tỉnh', 'tinh_nam_dinh', 228, '[]'),
       (25, 'Tỉnh Ninh Bình', 37, 'tỉnh', 'tinh_ninh_binh', 229, '[]'),
       (26, 'Tỉnh Thanh Hóa', 38, 'tỉnh', 'tinh_thanh_hoa', 237, '[]'),
       (27, 'Tỉnh Nghệ An', 40, 'tỉnh', 'tinh_nghe_an', 238, '[]'),
       (28, 'Tỉnh Hà Tĩnh', 42, 'tỉnh', 'tinh_ha_tinh', 239, '[]'),
       (29, 'Tỉnh Quảng Bình', 44, 'tỉnh', 'tinh_quang_binh', 232, '[]'),
       (30, 'Tỉnh Quảng Trị', 45, 'tỉnh', 'tinh_quang_tri', 233, '[]'),
       (31, 'Tỉnh Thừa Thiên Huế', 46, 'tỉnh', 'tinh_thua_thien_hue', 234, '[]'),
       (32, 'Thành phố Đà Nẵng', 48, 'thành phố trung ương', 'thanh_pho_da_nang', 236, '[]'),
       (33, 'Tỉnh Quảng Nam', 49, 'tỉnh', 'tinh_quang_nam', 235, '[]'),
       (34, 'Tỉnh Quảng Ngãi', 51, 'tỉnh', 'tinh_quang_ngai', 255, '[]'),
       (35, 'Tỉnh Bình Định', 52, 'tỉnh', 'tinh_binh_dinh', 256, '[]'),
       (36, 'Tỉnh Phú Yên', 54, 'tỉnh', 'tinh_phu_yen', 257, '[]'),
       (37, 'Tỉnh Khánh Hòa', 56, 'tỉnh', 'tinh_khanh_hoa', 258, '[]'),
       (38, 'Tỉnh Ninh Thuận', 58, 'tỉnh', 'tinh_ninh_thuan', 259, '[]'),
       (39, 'Tỉnh Bình Thuận', 60, 'tỉnh', 'tinh_binh_thuan', 252, '[]'),
       (40, 'Tỉnh Kon Tum', 62, 'tỉnh', 'tinh_kon_tum', 260, '[]'),
       (41, 'Tỉnh Gia Lai', 64, 'tỉnh', 'tinh_gia_lai', 269, '[]'),
       (42, 'Tỉnh Đắk Lắk', 66, 'tỉnh', 'tinh_dak_lak', 262, '[]'),
       (43, 'Tỉnh Đắk Nông', 67, 'tỉnh', 'tinh_dak_nong', 261, '[]'),
       (44, 'Tỉnh Lâm Đồng', 68, 'tỉnh', 'tinh_lam_dong', 263, '[]'),
       (45, 'Tỉnh Bình Phước', 70, 'tỉnh', 'tinh_binh_phuoc', 271, '[]'),
       (46, 'Tỉnh Tây Ninh', 72, 'tỉnh', 'tinh_tay_ninh', 276, '[]'),
       (47, 'Tỉnh Bình Dương', 74, 'tỉnh', 'tinh_binh_duong', 274, '[]'),
       (48, 'Tỉnh Đồng Nai', 75, 'tỉnh', 'tinh_dong_nai', 251, '[]'),
       (49, 'Tỉnh Bà Rịa - Vũng Tàu', 77, 'tỉnh', 'tinh_ba_ria_vung_tau', 254, '[]'),
       (50, 'Thành phố Hồ Chí Minh', 79, 'thành phố trung ương', 'thanh_pho_ho_chi_minh', 28, '[]'),
       (51, 'Tỉnh Long An', 80, 'tỉnh', 'tinh_long_an', 272, '[]'),
       (52, 'Tỉnh Tiền Giang', 82, 'tỉnh', 'tinh_tien_giang', 273, '[]'),
       (53, 'Tỉnh Bến Tre', 83, 'tỉnh', 'tinh_ben_tre', 275, '[]'),
       (54, 'Tỉnh Trà Vinh', 84, 'tỉnh', 'tinh_tra_vinh', 294, '[]'),
       (55, 'Tỉnh Vĩnh Long', 86, 'tỉnh', 'tinh_vinh_long', 270, '[]'),
       (56, 'Tỉnh Đồng Tháp', 87, 'tỉnh', 'tinh_dong_thap', 277, '[]'),
       (57, 'Tỉnh An Giang', 89, 'tỉnh', 'tinh_an_giang', 296, '[]'),
       (58, 'Tỉnh Kiên Giang', 91, 'tỉnh', 'tinh_kien_giang', 297, '[]'),
       (59, 'Thành phố Cần Thơ', 92, 'thành phố trung ương', 'thanh_pho_can_tho', 292, '[]'),
       (60, 'Tỉnh Hậu Giang', 93, 'tỉnh', 'tinh_hau_giang', 293, '[]'),
       (61, 'Tỉnh Sóc Trăng', 94, 'tỉnh', 'tinh_soc_trang', 299, '[]'),
       (62, 'Tỉnh Bạc Liêu', 95, 'tỉnh', 'tinh_bac_lieu', 291, '[]'),
       (63, 'Tỉnh Cà Mau', 96, 'tỉnh', 'tinh_ca_mau', 290, '[]');
